# Generated by Django 5.0.14 on 2025-06-20 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('vendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('endereco', models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço')),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsável')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Local de Estoque',
                'verbose_name_plural': 'Locais de Estoque',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='TipoMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=1, verbose_name='Tipo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Movimentação',
                'verbose_name_plural': 'Tipos de Movimentação',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('data_inventario', models.DateField(verbose_name='Data do Inventário')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim')),
                ('status', models.CharField(choices=[('PLANEJADO', 'Planejado'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PLANEJADO', max_length=20, verbose_name='Status')),
                ('responsavel', models.CharField(max_length=100, verbose_name='Responsável')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('usuario_criacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Criação')),
                ('local_estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.localestoque', verbose_name='Local de Estoque')),
            ],
            options={
                'verbose_name': 'Inventário',
                'verbose_name_plural': 'Inventários',
                'ordering': ['-data_inventario', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='ReservaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_reservada', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantidade Reservada')),
                ('quantidade_liberada', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Quantidade Liberada')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('data_reserva', models.DateTimeField(auto_now_add=True, verbose_name='Data da Reserva')),
                ('data_liberacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Liberação')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.itempedidovenda', verbose_name='Item do Pedido')),
                ('local_estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.localestoque', verbose_name='Local de Estoque')),
                ('pedido_venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.pedidovenda', verbose_name='Pedido de Venda')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.produto', verbose_name='Produto')),
                ('usuario_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário da Reserva')),
            ],
            options={
                'verbose_name': 'Reserva de Produto',
                'verbose_name_plural': 'Reservas de Produtos',
                'ordering': ['-data_reserva'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('data_movimentacao', models.DateTimeField(verbose_name='Data da Movimentação')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantidade')),
                ('quantidade_anterior', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Quantidade Anterior')),
                ('quantidade_atual', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Quantidade Atual')),
                ('custo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Custo Unitário')),
                ('custo_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Custo Total')),
                ('documento_referencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Documento de Referência')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.fornecedor', verbose_name='Fornecedor')),
                ('local_estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.localestoque', verbose_name='Local de Estoque')),
                ('pedido_venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.pedidovenda', verbose_name='Pedido de Venda')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.produto', verbose_name='Produto')),
                ('usuario_criacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Criação')),
                ('tipo_movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.tipomovimentacao', verbose_name='Tipo de Movimentação')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_movimentacao', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_sistema', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Quantidade no Sistema')),
                ('quantidade_contada', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Quantidade Contada')),
                ('diferenca', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Diferença')),
                ('custo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Custo Unitário')),
                ('valor_diferenca', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor da Diferença')),
                ('conferido', models.BooleanField(default=False, verbose_name='Conferido')),
                ('ajustado', models.BooleanField(default=False, verbose_name='Ajustado')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_contagem', models.DateTimeField(blank=True, null=True, verbose_name='Data da Contagem')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.inventario', verbose_name='Inventário')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.produto', verbose_name='Produto')),
                ('usuario_contagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário da Contagem')),
            ],
            options={
                'verbose_name': 'Item de Inventário',
                'verbose_name_plural': 'Itens de Inventário',
                'ordering': ['inventario', 'produto'],
                'unique_together': {('inventario', 'produto')},
            },
        ),
        migrations.CreateModel(
            name='EstoqueProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_atual', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Quantidade Atual')),
                ('quantidade_reservada', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Quantidade Reservada')),
                ('quantidade_disponivel', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Quantidade Disponível')),
                ('custo_medio', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Custo Médio')),
                ('data_ultima_movimentacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Última Movimentação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.produto', verbose_name='Produto')),
                ('local_estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.localestoque', verbose_name='Local de Estoque')),
            ],
            options={
                'verbose_name': 'Estoque de Produto',
                'verbose_name_plural': 'Estoque de Produtos',
                'ordering': ['produto', 'local_estoque'],
                'unique_together': {('produto', 'local_estoque')},
            },
        ),
        migrations.CreateModel(
            name='ProdutoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_fornecedor', models.CharField(max_length=50, verbose_name='Código do Fornecedor')),
                ('descricao_fornecedor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição do Fornecedor')),
                ('preco_compra', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Preço de Compra')),
                ('prazo_entrega_dias', models.IntegerField(default=0, verbose_name='Prazo de Entrega (dias)')),
                ('quantidade_minima', models.DecimalField(decimal_places=3, default=1, max_digits=15, verbose_name='Quantidade Mínima')),
                ('fornecedor_principal', models.BooleanField(default=False, verbose_name='Fornecedor Principal')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_ultima_compra', models.DateField(blank=True, null=True, verbose_name='Data da Última Compra')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.fornecedor', verbose_name='Fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Produto x Fornecedor',
                'verbose_name_plural': 'Produtos x Fornecedores',
                'ordering': ['produto', 'fornecedor'],
                'unique_together': {('produto', 'fornecedor')},
            },
        ),
    ]
