# Generated by Django 5.0.14 on 2025-06-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomovimentacao',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código'),
        ),
    ]
