# Generated by Django 5.0.14 on 2025-06-20 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Status de Orçamento',
                'verbose_name_plural': 'Status de Orçamentos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='StatusPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Status de Pedido',
                'verbose_name_plural': 'Status de Pedidos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('data_orcamento', models.DateField(verbose_name='Data do Orçamento')),
                ('data_validade', models.DateField(verbose_name='Data de Validade')),
                ('valor_produtos', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor dos Produtos')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor do Desconto')),
                ('percentual_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Percentual de Desconto')),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor do Frete')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Total')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('observacoes_internas', models.TextField(blank=True, null=True, verbose_name='Observações Internas')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.cliente', verbose_name='Cliente')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.formapagamento', verbose_name='Forma de Pagamento')),
                ('usuario_criacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Criação')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.vendedor', verbose_name='Vendedor')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.statusorcamento', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-data_orcamento', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Preço Unitário')),
                ('percentual_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Desconto (%)')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor do Desconto')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Total')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.produto', verbose_name='Produto')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.orcamento', verbose_name='Orçamento')),
            ],
            options={
                'verbose_name': 'Item de Orçamento',
                'verbose_name_plural': 'Itens de Orçamento',
                'ordering': ['orcamento', 'produto'],
            },
        ),
        migrations.CreateModel(
            name='PedidoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('data_pedido', models.DateField(verbose_name='Data do Pedido')),
                ('data_entrega_prevista', models.DateField(verbose_name='Data de Entrega Prevista')),
                ('data_entrega_realizada', models.DateField(blank=True, null=True, verbose_name='Data de Entrega Realizada')),
                ('valor_produtos', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor dos Produtos')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor do Desconto')),
                ('percentual_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Percentual de Desconto')),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor do Frete')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Total')),
                ('percentual_comissao', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Percentual de Comissão')),
                ('valor_comissao', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor da Comissão')),
                ('comissao_paga', models.BooleanField(default=False, verbose_name='Comissão Paga')),
                ('data_pagamento_comissao', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento da Comissão')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('observacoes_internas', models.TextField(blank=True, null=True, verbose_name='Observações Internas')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.cliente', verbose_name='Cliente')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.formapagamento', verbose_name='Forma de Pagamento')),
                ('orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.orcamento', verbose_name='Orçamento')),
                ('usuario_criacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Criação')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.vendedor', verbose_name='Vendedor')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.statuspedido', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Pedido de Venda',
                'verbose_name_plural': 'Pedidos de Venda',
                'ordering': ['-data_pedido', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantidade')),
                ('quantidade_entregue', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Quantidade Entregue')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Preço Unitário')),
                ('percentual_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Desconto (%)')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor do Desconto')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Total')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.produto', verbose_name='Produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.pedidovenda', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item de Pedido de Venda',
                'verbose_name_plural': 'Itens de Pedido de Venda',
                'ordering': ['pedido', 'produto'],
            },
        ),
        migrations.CreateModel(
            name='MetaVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('mes', models.IntegerField(verbose_name='Mês')),
                ('meta_valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Meta de Valor')),
                ('meta_quantidade', models.IntegerField(default=0, verbose_name='Meta de Quantidade de Vendas')),
                ('realizado_valor', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Realizado')),
                ('realizado_quantidade', models.IntegerField(default=0, verbose_name='Quantidade Realizada')),
                ('percentual_valor', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Percentual de Valor (%)')),
                ('percentual_quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Percentual de Quantidade (%)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.vendedor', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Meta de Vendedor',
                'verbose_name_plural': 'Metas de Vendedores',
                'ordering': ['-ano', '-mes', 'vendedor'],
                'unique_together': {('vendedor', 'ano', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='ComissaoVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor da Venda')),
                ('percentual_comissao', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentual de Comissão')),
                ('valor_comissao', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor da Comissão')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('usuario_criacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Criação')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.vendedor', verbose_name='Vendedor')),
                ('pedido_venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.pedidovenda', verbose_name='Pedido de Venda')),
            ],
            options={
                'verbose_name': 'Comissão de Vendedor',
                'verbose_name_plural': 'Comissões de Vendedores',
                'ordering': ['-data_vencimento', 'vendedor'],
                'unique_together': {('vendedor', 'pedido_venda')},
            },
        ),
    ]
